### PR TITLE
1775 refactoring remove limitation for the first discipline to be only from char gen

### LINKED ISSUE #1775: [REFACTORING]-remove limitation for the first discipline to be only from char gen
its unhandy and in case of starting as a questor it is wrong to prohibit the drop for the first discipline outside of the char gen

### PR DESCRIPTION
**Pull request by patrickmohrmann**
resolves #1775

### CODE REVIEW

File: module/data/item/discipline.mjs [hunk 1]
```diff
@@ -320,10 +320,6 @@ export default class DisciplineData extends ClassTemplate.mixin(
       ui.notifications.warn( game.i18n.localize( "ED.Notifications.Warn.cannotLearn" ) );
       return;
     }
-    if ( isEmpty( actor.disciplines ) ) {
-      ui.notifications.warn( game.i18n.localize( "ED.Notifications.Warn.firstDisciplineViaCharGen" ) );
```
Comment (patrickmohrmann) [inline module/data/item/discipline.mjs:324]: remove only return and adapt comment you need to use char gen, otherwise attributes are not working etc.
