### PR TITLE
fix wound calculation for strain

### LINKED ISSUE #972: Strain shall never cause a wound
**Describe the bug**
adding a high amount of strain to an ability and executing it. a wound is created if woundthreshold is below the strain. This shall not happen

### PR DESCRIPTION
**Pull request by patrickmohrmann**
resolves #972 

strain never causes a wound and therefore never causes knockdown

in addition, a wound from standard damage is created if the damage is **equal** or higher

### CODE REVIEW

File: module/documents/actor.mjs [hunk 1]
```diff
@@ -632,7 +632,7 @@ export default class ActorEd extends Actor {
 
     const updates = { [`system.characteristics.health.damage.${ damageType }`]: newDamage };
 
-    if ( damageTaken > health.woundThreshold ) {
+    if ( damageTaken >= health.woundThreshold && options.isStrain !== true ) {
```
Comment (ChristopherSD) [inline module/documents/actor.mjs:635]: can be written as `&& !options.isStrain`

File: module/documents/actor.mjs [hunk 2]
```diff
@@ -662,7 +662,7 @@ export default class ActorEd extends Actor {
       ChatMessage.create( messageData );
     }
 
-    const knockdownTest = !this.system.condition.knockedDown && damageTaken >= health.woundThreshold + 5;
+    const knockdownTest = !this.system.condition.knockedDown && damageTaken >= health.woundThreshold + 5 && options.isStrain !== true;
```
Comment (ChristopherSD) [inline module/documents/actor.mjs:665]: can be written as `&& !options.isStrain`

**Review by ChristopherSD — CHANGES_REQUESTED** [review]

File: module/documents/actor.mjs (hunk 1 above)
Comment (patrickmohrmann) [reply module/documents/actor.mjs]: done

File: module/documents/actor.mjs (hunk 2 above)
Comment (patrickmohrmann) [reply module/documents/actor.mjs]: done

**Review by ChristopherSD — APPROVED** [review]
