### PR TITLE
roll fixes

### LINKED ISSUE #1233: [REFACTOR] - Attribute Roll
attribute roll throws an error:

base-sheet.mjs:175 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'dataset')
    at ActorSheetEdCharacter.rollable (base-sheet.mjs:175:49)
    at #onClickAction (foundry-esm.js:45097:58)
    at #onClick (foundry-esm.js:45058:53)

**Note** its worth creating at this point a new AttributeRollData (see attack roll)

### LINKED ISSUE #1234: [REFACTOR] - Ability Roll Error
Abilities (non attack functions) throw an error 

rollable.mjs:40 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'bind')
    at TalentData.roll (rollable.mjs:40:51)
    at ActorSheetEdCharacter.rollable (base-sheet.mjs:177:76)
    at #onClickAction (foundry-esm.js:45097:58)
    at #onClick (foundry-esm.js:45058:53)

**Note** its worth creating at this point a new AbilityRollData (see attack roll)

### PR DESCRIPTION
**Pull request by patrickmohrmann**
resolved #1233
resolved #1234
added getDifficulty to target parameter in attackroll

### CODE REVIEW

File: module/applications/actor/base-sheet.mjs [hunk 1]
```diff
@@ -179,10 +179,12 @@ export default class ActorSheetEd extends HandlebarsApplicationMixin( DocumentSh
   static async rollable( event, target ) {
     event.preventDefault();
     const li = target.closest( ".item-id" );
-    const ability = this.document.items.get( li.dataset.itemId );
+    let ability;
+    if ( li ) {
+      ability = this.document.items.get( li.dataset.itemId );
```
Comment (ChristopherSD) [inline module/applications/actor/base-sheet.mjs:184]: I think this can be written as before but with optional chaining:
`const ability = this.document.items.get( li?.dataset?.itemId );`

**Review by ChristopherSD — CHANGES_REQUESTED** [review]

File: module/applications/actor/base-sheet.mjs (hunk 1 above)
Comment (patrickmohrmann) [reply module/applications/actor/base-sheet.mjs]: yes true, if fixed that

**Review by ChristopherSD — APPROVED** [review]
