### PR TITLE
fixed trigger reaction story

### LINKED ISSUE #653: trigger reaction (button / reaction option prompt)
**Description**
- [x] the chat output of the attack will have a button **Reaction**. 
- [x] this button might be greyed out if no reactive ability is available at the target. (optional)
- [x] if the targets owner (or GM) clicks on the button, a prompt will appear with all defensive abilities listed as buttons. 
- [] ~tool tips of the button shall show the description of the ability~ (done in #954 )

**Additional context**

### PR DESCRIPTION
**Pull request by patrickmohrmann**
resolves #653

### CODE REVIEW

File: module/data/item/templates/targeting.mjs [hunk 1]
```diff
@@ -53,7 +53,7 @@ export default class TargetTemplate extends SystemDataModel {
     let currentTarget = game.user.targets.first()?.actor;
     let currentTargets = [ ...game.user.targets.map( ( t ) => t.actor ) ];
     let numTargets = game.user.targets.size;
-    let targetDifficultySetting = this.difficulty.target;
+    let targetDifficultySetting = this.difficulty.target === "" ? 0 : this.difficulty.target;
```
Comment (ChristopherSD) [inline module/data/item/templates/targeting.mjs:56]: Can be simplified to 
`let targetDifficultySetting = this.difficulty.target || 0;`

Also, why is the default a `0`? This should be a valid key for the defenses, which 0 isn't. If you wanna say that we dont have that key, then semantically it would be better to use `undefined`, or in some cases `null`.
And this should be the case when it's not defined. This means we need to adjust the data model for that. It shouldn't be `blank`, but rather `required = false`.
If so, we don't need this variable at all.

File: module/data/item/templates/targeting.mjs [hunk 2]
```diff
@@ -75,7 +75,7 @@ export default class TargetTemplate extends SystemDataModel {
           baseDifficulty = TargetTemplate._getAggregatedDefense( currentTargets, targetDifficultySetting, Math.min );
           break;
         default:
-          baseDifficulty = currentTarget?.system.characteristics.defenses[targetDifficultySetting].value ?? 0;
+          baseDifficulty = targetDifficultySetting === 0 ? 0 : currentTarget?.system.characteristics.defenses[targetDifficultySetting].value ?? 0;
```
Comment (ChristopherSD) [inline module/data/item/templates/targeting.mjs:78]: See comments above about the `targetDifficultySetting` variable.
This line can be simplified either way:

**Review by ChristopherSD — CHANGES_REQUESTED** [review]

File: module/data/item/templates/targeting.mjs (hunk 1 above)
Comment (patrickmohrmann) [reply module/data/item/templates/targeting.mjs]: ok

File: module/data/item/templates/targeting.mjs (hunk 2 above)
Comment (patrickmohrmann) [reply module/data/item/templates/targeting.mjs:79]: ok

Comment (ChristopherSD) [reply module/data/item/templates/targeting.mjs:79]: This needs to be fixed. `targetDifficultySetting` can't be zero. It's  a string.
From what I understand you wanna achieve something like this?
```ecmascript 6
baseDifficulty = currentTarget?.system.characteristics.defenses[targetDifficultySetting]?.value ?? 0;
```

Comment (patrickmohrmann) [reply module/data/item/templates/targeting.mjs:79]: ok, understood

**Review by ChristopherSD — APPROVED** [review]
